const styles = [
  "Oil Painting",
  "Bauhaus",
  "Ukiyo-e",
  "Minimalist Line Art",
  "Cyberpunk",
  "Art Nouveau",
  "Impressionist",
  "Abstract Expressionism",
  "Surrealist",
  "Vintage Poster",
  "Watercolor",
  "Digital Art",
  "Sketch",
  "Pop Art",
  "Cubist",
  "Art Deco",
  "Baroque",
  "Renaissance",
  "Modernist",
  "Post-Impressionist",
  "Fauvist",
  "Expressionist",
  "Neo-Classical",
  "Romantic",
  "Gothic",
  "Japanese Woodblock",
  "Chinese Ink Painting",
  "African Tribal Art",
  "Native American Art",
  "Islamic Geometric",
  "Byzantine",
  "Pre-Raphaelite",
  "Steampunk",
  "Biomorphic",
  "Op Art",
  "Graffiti",
  "Calligraphy",
  "Collage",
  "Photorealistic",
  "Stained Glass",
];

const subjects = [
  "Old Vineyard",
  "Mythical Dragon",
  "Geometry",
  "Moon",
  "Grapes",
  "Mountain Landscape",
  "Floral Pattern",
  "Celestial Bodies",
  "Architectural Elements",
  "Nature Scene",
  "Sunset",
  "Ocean Waves",
  "Forest",
  "Desert",
  "City Skyline",
  "Ancient Ruins",
  "Castle",
  "Bridge",
  "Waterfall",
  "Aurora",
  "Stars",
  "Planets",
  "Birds",
  "Butterflies",
  "Fish",
  "Horses",
  "Lions",
  "Wolves",
  "Elephants",
  "Peacocks",
  "Vines",
  "Leaves",
  "Branches",
  "Roots",
  "Crystals",
  "Gems",
  "Fire",
  "Water",
  "Wind",
  "Earth",
  "Abstract Shapes",
  "Spirals",
  "Mandalas",
  "Symmetry",
  "Asymmetry",
  "Textures",
  "Patterns",
  "Shadows",
  "Light Rays",
  "Mist",
  "Fog",
  "Rain",
  "Snow",
  "Autumn Leaves",
  "Cherry Blossoms",
  "Roses",
  "Lilies",
  "Orchids",
  "Sunflowers",
  "Lotus",
  "Bamboo",
  "Pine Trees",
  "Olive Branches",
];

const moods = [
  "Dark & Moody",
  "Vivid",
  "Pastel",
  "Elegant",
  "Bold",
  "Serene",
  "Dramatic",
  "Whimsical",
  "Mysterious",
  "Ethereal",
  "Luxurious",
  "Rustic",
  "Modern",
  "Vintage",
  "Classic",
  "Contemporary",
  "Romantic",
  "Melancholic",
  "Joyful",
  "Tranquil",
  "Energetic",
  "Sophisticated",
  "Playful",
  "Sublime",
  "Mystical",
  "Nostalgic",
  "Futuristic",
  "Timeless",
  "Opulent",
  "Minimal",
  "Rich",
  "Subtle",
  "Intense",
  "Gentle",
  "Powerful",
  "Delicate",
  "Striking",
  "Harmonious",
];

/**
 * Generates a random artistic prompt for wine label design
 * @returns A formatted prompt string for image generation
 */
export function generateArtPrompt(): string {
  const randomStyle = styles[Math.floor(Math.random() * styles.length)];
  const randomSubject = subjects[Math.floor(Math.random() * subjects.length)];
  const randomMood = moods[Math.floor(Math.random() * moods.length)];

  return `A high quality artistic wine label design, no text, ${randomStyle} style, featuring ${randomSubject}, ${randomMood} mood`;
}

