const styles = [
  "hand-painted oil painting",
  "Bauhaus geometric design",
  "Japanese ukiyo-e woodblock print",
  "minimalist line drawing",
  "vintage Art Nouveau illustration",
  "impressionist brushwork",
  "abstract expressionist composition",
  "surrealist dreamscape",
  "retro poster art",
  "watercolor wash technique",
  "ink and wash painting",
  "charcoal sketch",
  "pop art screen print",
  "cubist deconstruction",
  "Art Deco elegance",
  "baroque ornamentation",
  "renaissance chiaroscuro",
  "modernist abstraction",
  "post-impressionist color",
  "fauvist bold palette",
  "expressionist emotion",
  "neo-classical refinement",
  "romantic landscape",
  "gothic detail",
  "Japanese woodblock tradition",
  "Chinese ink brush",
  "tribal pattern work",
  "geometric Islamic art",
  "Byzantine iconography",
  "Pre-Raphaelite detail",
  "steampunk machinery",
  "biomorphic forms",
  "op art illusion",
  "street art graffiti",
  "calligraphic brushwork",
  "collage assemblage",
  "stained glass window",
];

const subjects = [
  "Old Vineyard",
  "Mythical Dragon",
  "Geometry",
  "Moon",
  "Grapes",
  "Mountain Landscape",
  "Floral Pattern",
  "Celestial Bodies",
  "Architectural Elements",
  "Nature Scene",
  "Sunset",
  "Ocean Waves",
  "Forest",
  "Desert",
  "City Skyline",
  "Ancient Ruins",
  "Castle",
  "Bridge",
  "Waterfall",
  "Aurora",
  "Stars",
  "Planets",
  "Birds",
  "Butterflies",
  "Fish",
  "Horses",
  "Lions",
  "Wolves",
  "Elephants",
  "Peacocks",
  "Vines",
  "Leaves",
  "Branches",
  "Roots",
  "Crystals",
  "Gems",
  "Fire",
  "Water",
  "Wind",
  "Earth",
  "Abstract Shapes",
  "Spirals",
  "Mandalas",
  "Symmetry",
  "Asymmetry",
  "Textures",
  "Patterns",
  "Shadows",
  "Light Rays",
  "Mist",
  "Fog",
  "Rain",
  "Snow",
  "Autumn Leaves",
  "Cherry Blossoms",
  "Roses",
  "Lilies",
  "Orchids",
  "Sunflowers",
  "Lotus",
  "Bamboo",
  "Pine Trees",
  "Olive Branches",
];

const moods = [
  "deep shadowy tones",
  "vibrant saturated colors",
  "soft pastel hues",
  "refined elegance",
  "bold contrasting colors",
  "peaceful serenity",
  "theatrical drama",
  "whimsical charm",
  "enigmatic mystery",
  "otherworldly ethereal",
  "opulent luxury",
  "earthy rustic",
  "sleek modern",
  "aged vintage",
  "timeless classic",
  "cutting-edge contemporary",
  "romantic warmth",
  "melancholic depth",
  "joyful exuberance",
  "calm tranquility",
  "dynamic energy",
  "refined sophistication",
  "playful whimsy",
  "transcendent sublime",
  "mystical enchantment",
  "nostalgic memory",
  "futuristic vision",
  "enduring timeless",
  "lavish opulence",
  "sparse minimalism",
  "rich saturation",
  "understated subtlety",
  "intense passion",
  "gentle softness",
  "commanding power",
  "fragile delicacy",
  "arresting impact",
  "balanced harmony",
];

/**
 * Generates a random artistic prompt for wine label design
 * @returns A formatted prompt string for image generation
 */
export function generateArtPrompt(): string {
  const randomStyle = styles[Math.floor(Math.random() * styles.length)];
  const randomSubject = subjects[Math.floor(Math.random() * subjects.length)];
  const randomMood = moods[Math.floor(Math.random() * moods.length)];

  // More natural, human-like creative prompts that avoid AI-sounding phrases
  const creativeVariations = [
    `${randomStyle} wine label, ${randomSubject} rendered in ${randomMood}, hand-drawn illustration, vintage aesthetic, no text`,
    `Wine label in ${randomStyle} tradition, ${randomSubject} as central motif, ${randomMood} palette, artisanal craftsmanship, typography-free`,
    `${randomStyle} inspired wine label, ${randomSubject} composition, ${randomMood} atmosphere, traditional printmaking, textless design`,
    `Handcrafted wine label, ${randomStyle} approach, ${randomSubject} theme, ${randomMood} mood, artistic illustration, no lettering`,
    `Wine label artwork, ${randomStyle} technique, featuring ${randomSubject}, ${randomMood} color scheme, hand-painted feel, sans text`,
    `Artisanal wine label design, ${randomStyle} style, ${randomSubject} depicted with ${randomMood} sensibility, hand-illustrated, text-free`,
    `Wine label illustration, ${randomStyle} method, ${randomSubject} rendered in ${randomMood}, traditional craft, no typography`,
  ];

  return creativeVariations[Math.floor(Math.random() * creativeVariations.length)];
}

